class DebugEventHandler: EventHandler {

  /*override void worldTick() {
    if(Level.mapTime % (TICRATE*1) == 0) {           
      Console.printf("%i",Level.compatflags);
    }
  }*/
}
class VectorStaticEventHandler : StaticEventHandler {

  override void NetworkProcess(ConsoleEvent e) {

    // Autosave
    if(e.name == "quicksavevector") {

      let d = Dawn(players[0].mo);

      if(d && VectorStaticEventHandler.saveDisabled()) {
        d.denySave("$DENIEDSAVE_VECTOR", true);
        return;
      }
      
      EventHandler.SendNetworkEvent("quicksaveselaco");
      
      return;
    }
  }

  static clearscope bool saveDisabled() {
    return Level.info.flags & LEVEL_MAP07SPECIAL;
  }
}


enum VectorState {
  NOT_RUNNING,
  COUNT_DOWN_TO_NEXT_WAVE,
  RUNNING,
  END_WAVE,
  WORKSHOP_PRIZE_PAUSE,
  DEAD,
  COUNT_DOWN_TO_RESPAWN,
  GAME_OVER
}

class VectorEnemyClass {
  string name;
  int chance;

  static VectorEnemyClass create(string name, int chance) {
    let val=new("VectorEnemyClass");
    val.name=name;
    val.chance=chance;
    return val;
  }

}

class VectorPrizeCategory {
  string category;
  int chance;
  array<class<actor> > prizes;
}

class VectorEventHandler : EventHandler {

  const COUNT_DOWN_TIMER = TICRATE*4;
  const MINIMUM_DISTANCE_FROM_PLAYER = 500.0;
  const RANDOM_ALERT_CHANCE=40;

  const MIN_ENEMIES_PER_WAVE=3;
  const MAX_ENEMIES_PER_WAVE=10;

  const WAVES_BEFORE_HARDER_INVASION_TIER=3;
  const WAVES_BEFORE_HARDER_ENEMY_TIER=10;

  //[tier][soldier class]
  array<VectorEnemyClass> ENEMY_TIERS[3];

  int deathCountdown;
  int invincibleCountdown;
  int countDown;

  int maxLives;
  int currentLives;
  int currentWave;
  
  array<Actor> enemies;
  array<VectorPoint> playerRespawns;
  VectorPoint playerRespawnForPrize;
  array<VectorPoint> prizeRespawns;
  VectorPoint workshopRespawn;
  array<Actor> enemyRespawns;
  VectorWorkshop workshop;
  array<VectorPrize> prizes;
  array<VectorPerk> activePerks;
  array<VectorPrizeCategory > prizeClassesTier[3];

  // TODO use these for detonate bomb mode
  int useBarStartTime;
  int useBarDuration;

  VectorState vstate;
  VectorState nextState;
  int timerNextNetworkEvent;
  string nextNetworkEvent;

  static VectorEventHandler Instance() {
        return VectorEventHandler(EventHandler.Find("VectorEventHandler"));
  }

  ui static VectorEventHandler InstanceUI() {
        return VectorEventHandler(EventHandler.Find("VectorEventHandler"));
  }

  // LevelEventHandler order is 0, so I just run this eventhandler right after the Selaco one
  override void OnRegister() {
    SetOrder(1);
  }

  static void showVectorMenu() {
    Menu.setMenu("VectorMenu");
  } 	

  static void showVectorWorkshopMenu() {
    Menu.setMenu("VectorWorkshopMenu");
  } 	

  static void startVectorGameFromACS() {
    VectorEventHandler.Instance().startVectorNextWave();
  }

  void initEnemyTiers() {

    int tier;
    // 1 tier
    tier=0;
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SOLDIER", 45));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("ENGINEER", 20));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("CRAWLERMINE", 20));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SAWDRONE", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SOLDIER_SQUADLEADER", 5));

    // 2 tier
    tier=1;
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SOLDIER_SQUADLEADER", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SOLDIER", 30));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("ENGINEER", 20));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("GUNNER", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SIEGER", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("CRAWLERMINE", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SAWDRONE", 10));

    // 3 tier
    tier=2;
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SOLDIER_SQUADLEADER", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("ENFORCER", 20));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("PLASMATROOPER", 20));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("ENGINEER", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("GUNNER", 10));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("SIEGER", 15));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("CRAWLERMINEQUEEN", 5));
    ENEMY_TIERS[tier].push(VectorEnemyClass.create("AIRDRONE", 10));

  }

  void initPrizeClassesTiers() {

    for(int i=0; i<prizeClassesTier.size(); i++ ) {
      prizeClassesTier[i].clear();
    }

    //registering all prizes
    for(int i=0; i<AllActorClasses.size(); i++) {
      let act = AllActorClasses[i];
      if(act is "VectorPrize" && !act.IsAbstract()) {
        Console.Printf("Registering prize class %s", act.GetClassName());
        int tier = VectorPrize(GetDefaultbyType(act)).tier-1;
        string category = VectorPrize(GetDefaultbyType(act)).category;
        VectorPrizeCategory item;
        for(int j=0; j<prizeClassesTier[tier].size(); j++) {
          if(prizeClassesTier[tier][j].category == category) {
            item=prizeClassesTier[tier][j];
            break;
          }
        }
        if(!item) {
          item=new("VectorPrizeCategory");
          item.category=category;
          if(category=="stats") {
            item.chance=35;
          } else if (category=="weapon") {
            item.chance=30;
          } else if (category=="powerup") {
            item.chance=5;
          } else if (category=="upgrade") {
            item.chance=30;
          }
          prizeClassesTier[tier].push(item);
        }
        item.prizes.push(act);
      }
    }

    Console.printf("Generated the following prize tiers:");

    for(int i=0;i<prizeClassesTier.size();i++) {
      Console.printf("\n\nPrizes tier %i", i+1);
      for(int j=0;j<prizeClassesTier[i].size();j++) {
        Console.printf("\ncategory %s with chance %i", prizeClassesTier[i][j].category, prizeClassesTier[i][j].chance);
        for(int k=0;k<prizeClassesTier[i][j].prizes.size();k++) {
          Console.printf(prizeClassesTier[i][j].prizes[k].getClassName());
        }
      }
    }
  }

  void resetInvasionTier() {
    let tierItem = InvasionTierSystem.Instance().tierItem;
    for(int x=tierItem.tiers.size()-1;x>0;x--) {
      if(tierItem.tiers[x]) {
          tierItem.tiers[x].unlocked=false;
      }
    }            
  }

  void clean() {

    static const string ACT_TO_DELETE[] = { "Selaco_Blood", "Selaco_BloodSpot", "Goremaster", "Decalleader", "Crawlerleg", "CrawlerDeath1", "Sawdronesaw", "Sawdronewing", "EnemyWeaponModel", "EnemyGrenadeDecorationMissile", "Ammopickup" };

    for(int i=0; i<ACT_TO_DELETE.size(); i++) {
      Actor act;
      ThinkerIterator it = ThinkerIterator.Create(ACT_TO_DELETE[i]);
      while(act = Actor(it.Next())) {
        act.destroy();
      }
    }
  }

  override void WorldLoaded(WorldEvent e) {

    console.printf("VECTOR EVENT HANDLER WORLD LOADED -> BEGIN");

    initEnemyTiers();
    initPrizeClassesTiers();

    deathCountdown = -1;

    maxLives=3;
    
    vstate=NOT_RUNNING;

    timerNextNetworkEvent=-1;

    // add the pda entry that explains how V.E.C.T.O.R. works
    PDAManager.AddEntry(players[consoleplayer].mo, 0, 61, true);

    // registering all respawns
    VectorPoint vp;
    ThinkerIterator it = ThinkerIterator.Create("VectorPrizeRespawn");
    while(vp = VectorPoint(it.Next())) {
        prizeRespawns.Push(vp);      
    }

    it = ThinkerIterator.Create("PathNode");
    Actor node;
    while(node = Actor(it.Next())) {
      enemyRespawns.Push(node);
    }

    it = ThinkerIterator.Create("VectorPlayerRespawnForPrize");
    playerRespawnForPrize=VectorPoint(it.Next());

    it = ThinkerIterator.Create("VectorWorkshopRespawn");
    workshopRespawn=VectorPoint(it.Next());

    workshop=VectorWorkshop(Actor.Spawn("VectorWorkshop", workshopRespawn.pos));

    initPlayer();
    resetPlayer();
    it = ThinkerIterator.Create("VectorPlayerRespawn");    
    while(vp = VectorPlayerRespawn(it.Next())) {
      playerRespawns.Push(vp);
    }
    it = ThinkerIterator.Create("VectorPlayerRespawnForPrize");
    playerRespawnForPrize=VectorPoint(it.Next());
    respawnPlayer(playerRespawnForPrize);
    
    console.printf("VECTOR EVENT HANDLER WORLD LOADED -> END");
  }

  override void uiTick() {
    if(countDown > 0 && !HUD.FindElement("HUDVectorCountDown")) {
      HUD.AddElement("HUDVectorCountDown");
    }

    if(!HUD.FindElement("HUDVectorUseBar")) {
      HUD.AddElement("HUDVectorUseBar");
    }

    if(vstate!=NOT_RUNNING && vstate!=GAME_OVER && !HUD.FindElement("HUDVectorInfo")) {
      HUD.AddElement("HUDVectorInfo");
    }

    if(!HUD.FindElement("HUDVectorPrizeDescription")) {
      HUD.AddElement("HUDVectorPrizeDescription");
    }
  }

  override void worldTick() {

    // Since an ACS script when a new map open, add the personal entries, I need this trick to remove those pda entries
    if (Level.maptime < 5) {
      PDAManager.RemoveEntry(players[consoleplayer].mo, 0, 1);
      PDAManager.RemoveEntry(players[consoleplayer].mo, 0, 2);
      PDAManager.RemoveEntry(players[consoleplayer].mo, 0, 3);
      PDAManager.RemoveEntry(players[consoleplayer].mo, 0, 4);
      PDAManager.RemoveEntry(players[consoleplayer].mo, 0, 5);
    }

    if(deathCountdown > 0 || (deathCountdown == 0 && players[consolePlayer].mo && players[consolePlayer].mo.health == 0)) {
      if(Level.maptime >= players[consolePlayer].respawn_time && 
         (
          players[consolePlayer].cmd.buttons & BT_ATTACK      || 
          players[consolePlayer].cmd.buttons & BT_ALTATTACK   || 
          players[consolePlayer].cmd.buttons & BT_USE         ||
          players[consolePlayer].cmd.buttons & BT_USER1       ||  
          --deathCountdown == 0
          )) {
        deathCountdown  = -1;

        if(vstate == DEAD) {
          countDown = COUNT_DOWN_TIMER;
          vstate=COUNT_DOWN_TO_RESPAWN;
        } else if(vstate == GAME_OVER) {
          // GAME OVER AFTER COUNT DOWN, RESET EVERYTHING
          initPrizeClassesTiers();
          startVectorPrize(false);
          resetPlayer();
          resetInvasionTier();
          clearPerks();
          clean();
          for(int i=0; i<enemies.Size(); i++) {
            if(enemies[i]){
              enemies[i].destroy();
            }
          }
          vstate=NOT_RUNNING;
        }
      }
    }

    // we are doing a countdown
    if(countDown > 0 ) {
      decrementCountDown();
    }

    // check enemies alive while wave is running
    if(vstate==RUNNING) {
      bool stillAlive=false;
      for(int i=0; i<enemies.Size(); i++) {
        if (enemies[i] && enemies[i].health>0) {
          stillAlive=true;
          break;
        }
      }
      if(!stillAlive) {

        // CHECK: enemies could have spawned other enemies, like turrets
        let it = ThinkerIterator.Create("SelacoEnemy");
        actor sentry;
        bool stillEnemies=false;
        while(sentry=Actor(it.next())) {
          enemies.push(sentry);
          stillEnemies=true;
        }

        if(!stillEnemies) {

          vstate=END_WAVE;    
          players[consoleplayer].mo.A_PLAYSOUND("announcer/waveC");
          printMessage("$VECTOR_MSG_END_WAVE");
          timerNextNetworkEvent=TICRATE*3;
          nextNetworkEvent="startVectorPrize";
          checkPerks();
        }
      }
    } else if(vstate==NOT_RUNNING || vstate==WORKSHOP_PRIZE_PAUSE) {      
        
      bool gotPrize=false;
      for(int i=0; i<prizes.Size(); i++) {
        if(!prizes[i]) {
          gotPrize=true;
          break;
        }
      }
      if(gotPrize) {
        for(int i=0; i<prizes.Size(); i++) {
          if(prizes[i]) {
            prizes[i].destroy();
          }
        }
        prizes.clear();
      }
      if(workshop && players[consoleplayer].mo.distance2d(workshop) > workshop.safearearadius) {
        startVectorNextWave();
      }

      // DEBUG: reroll prizes if I click right mouse button
      if (CVar.getcvar("sv_cheats").getBool() && players[consolePlayer].cmd.buttons & BT_ALTATTACK) {
        rerollPrizes();
      }
    }

    if(timerNextNetworkEvent > 0) {
      timerNextNetworkEvent--;
    } else if(timerNextNetworkEvent == 0) {
      timerNextNetworkEvent=-1;
      if(nextNetworkEvent) {
        EventHandler.SendNetworkEvent(nextNetworkEvent);
      }
    }

    /* I keep this code commented for when I will build the detonate bomb mode
    if ((vstate==NOT_RUNNING || vstate==END_WAVE) && (players[consolePlayer].cmd.buttons & BT_ALTATTACK)) {

      if(useBarStartTime > 0 && Level.mapTime > useBarStartTime + useBarDuration) {
        startVectorNextWave();
      } else if(useBarStartTime <=0){
        useBarStartTime = Level.mapTime;       
        useBarDuration = TICRATE*2;
      }
    } else {
      useBarStartTime=0;
    }*/
  }

  override void NetworkProcess(ConsoleEvent e) {  

    if(e.name.indexOf("VECTOR_ENABLE_UPGRADE:") == 0 ) {
      // Take resources
      let weaponUpgradeName = e.name.mid(22);
      players[consoleplayer].mo.TakeInventory("weaponparts", VectorWeaponUpgrades.GetUpgradeCost(weaponUpgradeName));
      WeaponUpgrade.SetUpgradeEnabled(weaponUpgradeName, e.player, true); 
    } else if(e.name.indexOf("VECTOR_DISABLE_UPGRADE:") == 0 ) {
      // Take resources
      let weaponUpgradeName = e.name.mid(23);
      players[consoleplayer].mo.GiveInventory("weaponparts", VectorWeaponUpgrades.GetUpgradeCost(weaponUpgradeName));
      WeaponUpgrade.SetUpgradeEnabled(weaponUpgradeName, e.player, false); 
    } else if(e.name == "startVectorPrize" ) {
      startVectorPrize();
    }
  }

  override void InterfaceProcess(ConsoleEvent e) {
    if (!e.isManual && e.name == "disable_bloody_ui") {
      let hud = HUD(StatusBar);
      hud.overlay.drawers[HUDOverlay.OV_DEATH].SetAlpha(0);
    }
  }

  void startVectorPrize(bool prize=true) {
    vstate=WORKSHOP_PRIZE_PAUSE;
    respawnPlayer(playerRespawnForPrize);    
    workshop=VectorWorkshop(Actor.Spawn("VectorWorkshop", workshopRespawn.pos));
    if(prize) {
      if(Random(1,100) <= 30) {
        Dawn d =Dawn(players[consoleplayer].mo);
        d.dawnTalk("dawn/cabinet");
      }
      rollPrizes();
    }
  }

  void rollPrizes() {
    
    for(int i=0; i<prizeRespawns.size(); i++) {
      int chance=Random(0,100);
      int tier;
      if(chance<70) {
        tier=0;
      } else if(chance<95) {
        tier=1;
      } else {
        tier=2;
      }
      Console.printf("Trying to get prize with tier %i", tier);
      
      int maxChance=0;
      for(int i=0; i<prizeClassesTier[tier].Size(); i++) {
        maxChance+=prizeClassesTier[tier][i].chance;
      }

      bool gotCategory=false;      
      int categoryIndex;
      int subSize;
      while(!gotCategory) {
        int result=Random(0,maxChance);
        int sum=0;

        for(int i=0; i<prizeClassesTier[tier].Size(); i++) {
          if(result <= prizeClassesTier[tier][i].chance+sum) {
            categoryIndex=i;
            break;
          } else {
            sum+=prizeClassesTier[tier][i].chance;
          }
        }
        subSize=prizeClassesTier[tier][categoryIndex].prizes.size();

        if(subSize>0) {
          gotCategory=true;
        }
      }

      bool gotPrize=false;
      int count=0;
      while(!gotPrize) {
        count++;
        int prizeIndex=Random(0,subsize-1);
        let prizeClass=VectorPrize(GetDefaultByType(prizeClassesTier[tier][categoryIndex].prizes[prizeIndex]));
        Console.printf("Got prize class %s", prizeClass.getClassName());
        if(count > 100 || prizeClass.CanPickUp(players[consoleplayer].mo)){
          gotPrize=true;
          for(int j=0;j<prizes.size();j++) {
            if(prizes[j].GetClassName() == prizeClass.GetClassName()) {
              gotPrize=false;
              break;
            }
          }
          if(count > 100 || gotPrize) {
            gotPrize=true;
            let prize=VectorPrize(Actor.Spawn(prizeClassesTier[tier][categoryIndex].prizes[prizeIndex], prizeRespawns[i].pos));
            prizes.push(prize);
            if(prize.oneTimeOnly) {
              prizeClassesTier[tier][categoryIndex].prizes.delete(prizeIndex);
            }
          }
        }
      }
    }
  }

  void reRollPrizes() {
    for(int i=0; i<prizes.Size(); i++) {
      if(prizes[i]) {
        prizes[i].destroy();
      }
    }
    prizes.clear();
    rollPrizes();

  }

  void startVectorNextWave() {

    if(vstate==NOT_RUNNING) {
      currentLives=maxLives;
      currentWave=0;
    }

    workshop.delete();
    for(int i=0; i<prizes.Size(); i++) {
      if(prizes[i]) {
        prizes[i].destroy();
      }
    }
    prizes.clear();

    vstate=COUNT_DOWN_TO_NEXT_WAVE;

    // move player to random respawn point
    respawnPlayer(playerRespawns[Random(0,playerRespawns.Size()-1)]);
    
    // block player
    Dawn(players[consoleplayer].mo).blockMovement=true;

    countDown = COUNT_DOWN_TIMER;

    currentWave++;

    players[consoleplayer].mo.A_PLAYSOUND("announcer/prepare", CHAN_AUTO);
    printMessage("$VECTOR_MSG_WAVE",string.format("%i", currentWave));

    int invasionTierCount=InvasionTierSystem.Instance().getInvasionTierCount();
    if(invasionTierCount ==0) {
      invasionTierCount=1;
    }
    if(currentWave>1 && invasionTierCount<INVTIER_COUNT &&((currentWave-1) % WAVES_BEFORE_HARDER_INVASION_TIER == 0)) {      
      InvasionTierSystem.Instance().setInvasionTier(invasionTierCount);
      printMessage("$VECTOR_MSG_INVASION_TIER", string.format("%i",InvasionTierSystem.Instance().getInvasionTierCount()-1));
    }
  }

  void respawnPlayer(VectorPoint respawn) {
    // if player is dead, resurrection
    let player = players[consolePlayer];
    if(player.mo.health <= 0) {
      player.mo.TakeInventory("PlayerIsDead", 1);
      player.mo.friction = 0.1;
      player.SetPSprite(PSP_OFFHAND, null );
      player.resurrect();
      // Disable that bloody UI
      EventHandler.SendInterfaceEvent(consolePlayer, "disable_bloody_ui");
    }

    // move player to respawn point
    player.mo.vel.x=0;player.mo.vel.y=0;player.mo.vel.z=0;
    player.mo.SetOrigin(respawn.pos, false);
    player.mo.angle = respawn.angle;
    player.mo.pitch = 0;
  }


  void decrementCountDown() {
    countDown--;

    PlayerPawn pawn=players[consoleplayer].mo;

    // BEEP...
    if(countDown % TICRATE == 0 && countDown != 0) {
        pawn.A_PLAYSOUND("SHOOTINGRANGE/COUNTDOWN", CHAN_AUTO, 0.3);
    }
		
    // BEEEEEEEEEEEEEP !!!
    if(countDown == 0) {
        pawn.A_PLAYSOUND("SHOOTINGRANGE/START", CHAN_AUTO, 0.4);
        Dawn d = Dawn(pawn);
        d.blockMovement=false;
        if(vstate==COUNT_DOWN_TO_NEXT_WAVE) {
          spawnEnemies();
          printMessage("$VECTOR_MSG_START_WAVE");
          if(random(1,100) <=30) {
            d.dawnTalk("DAWN/YOUGOTTHIS");
          }
        } else if (vstate==COUNT_DOWN_TO_RESPAWN) {          
          // make enemy forget player
          for(int i=0;i<enemies.size();i++) {
            if(enemies[i] && enemies[i] is "EnemySoldier") {
              EnemySoldier(enemies[i]).lostPlayerGoPatrol();
            }
          }
          //respawn player in a suitable place
          respawnPlayer(findSuitablePlayerRespawn());

          if(random(1,100) <=30) {
            d.dawnTalk("dawn/annoyed1");
          }
        }
        vstate=RUNNING;
    }
  }

  VectorPoint findSuitablePlayerRespawn() {
    bool checkDistance=true;
    bool checkSight=true;
    int count=0;
    VectorPoint respawn;
    Console.printf("Finding a good spot for player spawn");
    while(true) {
      count++;
      Console.printf("%d iteration", count);
      // after some iteration, I disable first the check distance, then the check sight
      if(count % 100 == 0) {
        if(checkDistance) {
          Console.printf("Can't find a good spot, trying to disable check distance");
          checkDistance=false;
        } else if(checkSight){
          Console.printf("Can't find a good spot, trying to disable check sight");
          checkSight=false;
        } else {
          //WORST SCENARIO! Just pick the first one. It should not happens. This means the pathnodes are not good
          Console.printf("WORST SCENARIO. Picking the first one");
          respawn=playerRespawns[0];
          break;
        }          
      }

      respawn = playerRespawns[Random(0,playerRespawns.Size()-1)];

      if(checkDistance) {
        bool failCheckDistance=false;
        for(int i=0; i<enemies.size(); i++) {
          if(enemies[i] && respawn.Distance2D(enemies[i]) <= MINIMUM_DISTANCE_FROM_PLAYER) {
            failCheckDistance=true;
            break;
          }
        }
        if(failCheckDistance) {
          Console.printf("Not good. Too close to player");
          continue;
        }
      }
      
      // I need to increase temporarily the height of the node, simulating the average height of an enemy. If I don't do that, "fences" can hide the nodes.
      int oldHeight = respawn.height;
      respawn.A_SetSize(-1, 120);

      if(checkSight) {
        bool failCheckSight=false;
        for(int i=0; i<enemies.size(); i++) {
          if(enemies[i] && respawn.CheckSight(enemies[i], SF_SEEPASTBLOCKEVERYTHING | SF_SEEPASTSHOOTABLELINES | SF_IGNOREVISIBILITY)) {
            failCheckSight=true;
            break;
          }
        }
        if(failCheckSight) {
          Console.printf("Not good. There is an enemy that could see the player");
          respawn.A_SetSize(-1, oldHeight);
          continue;
        }
      }
      respawn.A_SetSize(-1, oldHeight);
      
      break;
    }

    Console.printf("Found a good spot!");

    return respawn;
  }

  void spawnEnemies() {
   
    vstate=RUNNING;
    enemies.clear();
    array<Actor> enemyRespawnsWave;
    enemyRespawnsWave.copy(enemyRespawns);

    BattleOverseer overseer = BattleOverseer.Instance();
    BattleSquad newSquad;

    bool alert=Random(0,100)<=RANDOM_ALERT_CHANCE;

    int tier;
    if(currentWave < WAVES_BEFORE_HARDER_ENEMY_TIER) {
      tier=0;
    } else if(currentWave < WAVES_BEFORE_HARDER_ENEMY_TIER*2) {
      tier=1;
    } else if(currentWave < WAVES_BEFORE_HARDER_ENEMY_TIER*3) {
      tier=2;
    } else {
      tier=2;
    }

    // Getting the number of enemies, depending on the number of wave
    int enemiesCount=MIN_ENEMIES_PER_WAVE+((currentWave-1)%WAVES_BEFORE_HARDER_ENEMY_TIER);
    if(enemiesCount > MAX_ENEMIES_PER_WAVE) {
      enemiesCount=MAX_ENEMIES_PER_WAVE;
    }
    console.printf("Trying to spawn %i enemies", enemiesCount);
    bool squadLeaderSpawned=false;
    for(int i=0; i<enemiesCount; i++) {
      let spawnNodeIndex = findEnemyRespawn(enemyRespawnsWave);
      let enemyClass = findEnemyFromTier(tier,squadLeaderSpawned);
      if(enemyClass=="SOLDIER_SQUADLEADER") {
        squadLeaderSpawned=true;
      }
      console.printf("Trying to spawn %s enemy in node %i", enemyClass, spawnNodeIndex);
      let enemy = Actor.Spawn( enemyClass, enemyRespawnsWave[spawnNodeIndex].pos);
      enemy.angle=Random(0,360);
      enemyRespawnsWave.Delete(spawnNodeIndex);
      
      enemies.push(enemy);

      if(alert && enemy is "EnemySoldier") {
        EnemySoldier es = EnemySoldier(enemy);
        if(!newSquad) {
          newSquad = overseer.createNewBattleSquad(es);
          newSquad.squadStatus = SQUAD_PATROL;    
          newSquad.patrolStartTime = level.time;
        } else {
          overseer.assignSquad(es, newSquad);
        }      
        es.lostPlayerGoPatrol();

        if(es.squad && es.squad.members.size() && random(1, 1) == 1) {
          es.squad.assignCalloutToSquadmate(SOLDIER_SEARCH, urgent:true, ignoreSizeRequirement:false, delayOffset:3);
        }
      
      }
    }
  }

  override void WorldThingDied(WorldEvent e) {
    // TRICK: We need to destroy every credits bag that spawn after the dead of a squad leader
    if(e.thing is "Soldier_SquadLeader") {
      let it = ThinkerIterator.Create("CreditsbagSmall");
      actor bag;
      while(bag=Actor(it.next())) {
        if(bag) {
          bag.destroy();
        }
      }
    }
  }


  override void PlayerDied(PlayerEvent e) {

    if(e.PlayerNumber == consolePlayer) {

      // TRICK: When player die, I need LevelEventHandler not to manage the death of the player and call the DeathMenu
      if(deathCountdown < 0) {
        LevelEventHandler.instance().deathCountdown = -1;
        deathCountdown = TICRATE * 4;
      }
      currentLives--;
      if(currentLives > 0) {
        vstate=DEAD;
        let msg = "$VECTOR_MSG_DEAD";
        if(currentLives==1) {
          msg = "$VECTOR_MSG_DEAD_ONLY_1_LIFE";
        }
        printMessage(msg,string.format("%i",currentLives));
      } else {
        vstate=GAME_OVER;
        printMessage("$VECTOR_MSG_GAME_OVER");        
      }
    }
  }

  int findEnemyRespawn(array<Actor> enemyRespawnsWave) {
    
    bool checkDistance=true;
    bool checkSight=true;
    int count=0;
    int respawnIndex;
    let player = players[consolePlayer].mo;
    Console.printf("Finding a good spot for enemy spawn");
    while(true) {
      count++;
      Console.printf("%d iteration", count);
      // after some iteration, I disable first the check distance, then the check sight
      if(count % 100 == 0) {
        if(checkDistance) {
          Console.printf("Can't find a good spot, trying to disable check distance");
          checkDistance=false;
        } else if(checkSight){
          Console.printf("Can't find a good spot, trying to disable check sight");
          checkSight=false;
        } else {
          //WORST SCENARIO! Just pick the first one. It should not happens. This means the pathnodes are not good
          Console.printf("WORST SCENARIO. Picking the first one");
          respawnIndex = 0;
          break;
        }          
      }

      respawnIndex = Random(0,enemyRespawnsWave.Size()-1);

      let respawn = enemyRespawnsWave[respawnIndex];

      if(checkDistance && player.Distance2D(respawn) <= MINIMUM_DISTANCE_FROM_PLAYER) {
        Console.printf("Not good. Too close to player");
        continue;
      }
      
      // I need to increase temporarily the height of the node, simulating the average height of an enemy. If I don't do that, "fences" can hide the nodes.
      int oldHeight = respawn.height;
      respawn.A_SetSize(-1, 120);

      if(checkSight && player.CheckSight(respawn, SF_SEEPASTBLOCKEVERYTHING | SF_SEEPASTSHOOTABLELINES | SF_IGNOREVISIBILITY)) {
        Console.printf("Not good. Player can see this spot");
        respawn.A_SetSize(-1, oldHeight);
        continue;
      }
      respawn.A_SetSize(-1, oldHeight);
      break;
    }

    Console.printf("Found a good spot!");

    return respawnIndex;

  }

  string findEnemyFromTier(int enemyTier, bool squadLeaderSpawned) {
    
    int maxChance=0;
    for(int i=0; i<ENEMY_TIERS[enemyTier].Size(); i++) {
      maxChance+=ENEMY_TIERS[enemyTier][i].chance;
    }      

    int result=Random(0,maxChance);
    int sum=0;
    string enemyClass="";
    for(int i=0; i<ENEMY_TIERS[enemyTier].Size(); i++) {
      if(result <= ENEMY_TIERS[enemyTier][i].chance+sum) {
        enemyClass=ENEMY_TIERS[enemyTier][i].name;
        break;
      } else {
        sum+=ENEMY_TIERS[enemyTier][i].chance;
      }
    }

    if(enemyClass =="SOLDIER_SQUADLEADER" && squadLeaderSpawned) {
      enemyClass="SOLDIER";
    }

    // if we got SOLDIER, randomize his role.
    if(enemyClass == "SOLDIER") {
      switch (Random(1,4)) {
        case 1: enemyClass="SOLDIER_DEFENDER"; break;
        case 2: enemyClass="SOLDIER_ATTACKER"; break;
        case 3: enemyClass="SOLDIER_AGGRESSOR"; break;
        case 4: enemyClass="SOLDIER_STRAFER"; break;
      }
    }

    return enemyClass;
  }

  void ActivatePerk(string perkName) {
    let player=players[consoleplayer].mo;
    player.GiveInventory(perkName,1);
    VectorPerk perk = VectorPerk(player.FindInventory(perkName));
    activePerks.push(perk);
  }

  bool IsPerkActive(string perkName) {
    let player=players[consoleplayer].mo;
    Inventory inv = player.FindInventory(perkName);
    return inv && inv.amount > 0;
  }

  void checkPerks() {
    array<VectorPerk> perksToDelete;
    for(int i=0;i<activePerks.size();i++){
      Console.printf("Active Perk %s with wavesleft %i", activePerks[i].getClassName(), activePerks[i].wavesLeft);
      activePerks[i].wavesLeft--;
      if(activePerks[i].wavesLeft==0) {
        perksToDelete.push(activePerks[i]);
      }
    }

    for(int i=0;i<perksToDelete.size();i++){ 
      int index = activePerks.find(perksToDelete[i]);
      players[consoleplayer].mo.TakeInventory(activePerks[index].getClassName(),1);
      activePerks.delete(index);
    }

  }

  void clearPerks() {    
    for(int i=0;i<activePerks.size();i++){ 
      players[consoleplayer].mo.TakeInventory(activePerks[i].getClassName(),1);      
    }
    activePerks.clear();
  }

  void printMessage(string message, string arg="") {
    string localizedMessage = stringTable.localize(message);
    PlayerPawn pawn=players[consolePlayer].mo;
    let d = Dawn(pawn);   
    d.A_PRINTBOLD(string.format(localizedMessage,arg));
  }

}
